version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Temporal#123
      POSTGRES_DB: erp_bd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./Back-end
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://postgres:Temporal%23123@db:5432/erp_bd?schema=public
      - PORT=4000
    depends_on:
      - db

  frontend:
    build: ./Front-end
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
